version: '3.8'

services:
  mcp-server:
    build:
      context: ./mcp-server
    ports:
      - "8000:8000"
    env_file:
      - ./mcp-server/.env
    volumes:
      - ./mcp-server:/app

  streamlit-app:
    build:
      context: ./streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - mcp-server
    env_file:
      - ./mcp-server/.env  # Assuming it needs access to the API key too
    volumes:
      - ./streamlit-app:/app
