version: '3.8'

services:
  mcp-server:
    build: ./mcp-server
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./mcp-server:/app
    restart: unless-stopped

  streamlit-app:
    build: 
      context: ./streamlit-app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - MCP_SERVER_URL=http://mcp-server:8000
    depends_on:
      - mcp-server
    restart: unless-stopped